CREATE TABLE CUSTOMER
(
    ACCOUNT_NUMBER        BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID               VARCHAR(50) UNIQUE       NOT NULL,
    FIRST_NAME            VARCHAR(50)              NOT NULL,
    LAST_NAME             VARCHAR(50)              NOT NULL,
    FATHER_NAME           VARCHAR(50)              NOT NULL,
    FATHER_LAST_NAME      VARCHAR(50)              NOT NULL,
    AADHAAR_NUMBER        VARCHAR(12) UNIQUE       NOT NULL,
    PAN_NUMBER            VARCHAR(50) UNIQUE       NOT NULL,
    MOBILE_NUMBER         VARCHAR(10) UNIQUE       NOT NULL,
    EMAIL_ID              VARCHAR(100)   DEFAULT 'NA',
    ADDRESS               VARCHAR(100)             NOT NULL,
    CITY                  VARCHAR(50)              NOT NULL,
    STATE                 VARCHAR(80)              NOT NULL,
    PINCODE               VARCHAR(10)              NOT NULL,
    YEARLY_INCOME         DECIMAL(15, 2) DEFAULT 0,
    CURRENT_BALANCE       DECIMAL(15, 2) DEFAULT 0 NOT NULL,
    ACCOUNT_CREATION_DATE DATETIME       DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE CUSTOMER
    AUTO_INCREMENT = 100000000000;

CREATE TABLE LOGIN_INFO
(
    USER_ID        VARCHAR(50) PRIMARY KEY REFERENCES CUSTOMER (USER_ID),
    ACCOUNT_NUMBER BIGINT UNIQUE REFERENCES CUSTOMER (ACCOUNT_NUMBER),
    PASSWORD_HASH  VARCHAR(64) NOT NULL,
    PIN_HASH       VARCHAR(64) NOT NULL,
    CONSTRAINT FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES CUSTOMER (ACCOUNT_NUMBER),
    CONSTRAINT FOREIGN KEY (USER_ID) REFERENCES CUSTOMER (USER_ID)
);

CREATE TABLE TRANSACTION
(
    TRANSACTION_ID   BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DATE_TIME        DATETIME DEFAULT CURRENT_TIMESTAMP,
    ACCOUNT_NUMBER   BIGINT             NOT NULL,
    TRANSACTION_TYPE VARCHAR(10)        NOT NULL CHECK ( TRANSACTION_TYPE IN ('CREDIT', 'DEBIT') ),
    DESCRIPTION      VARCHAR(200),
    AMOUNT           DECIMAL(15, 2)     NOT NULL,
    CONSTRAINT FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES CUSTOMER (ACCOUNT_NUMBER)
);

CREATE TRIGGER UPDATE_BALANCE
    AFTER INSERT
    ON TRANSACTION
    FOR EACH ROW
BEGIN
    IF NEW.TRANSACTION_TYPE = 'CREDIT' THEN
        UPDATE CUSTOMER
        SET CURRENT_BALANCE = CURRENT_BALANCE + NEW.AMOUNT
        WHERE ACCOUNT_NUMBER = NEW.ACCOUNT_NUMBER;
    ELSEIF NEW.TRANSACTION_TYPE = 'DEBIT' THEN
        UPDATE CUSTOMER
        SET CURRENT_BALANCE = CURRENT_BALANCE - NEW.AMOUNT
        WHERE ACCOUNT_NUMBER = NEW.ACCOUNT_NUMBER;
    END IF;
END;

select * from LOGIN_INFO;
select * from customer;
select * from transaction;